/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "https://ogbnegwtqzijjwmkydwq.supabase.co"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nYm5lZ3d0cXppamp3bWt5ZHdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3NDc2MDcsImV4cCI6MjA3OTMyMzYwN30.N7c7eWvWo_RWS0A2TxfYVrcedEziD59T-PwCJby8Y3I"