import { Button } from "./ui/button";
import { Download, Printer } from "lucide-react";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "./ui/dropdown-menu";
import { Restaurant } from "../types/restaurant";
import { toast } from "sonner@2.0.3";

interface ExportButtonProps {
  restaurants: Restaurant[];
  type: "favorites" | "comparison" | "all";
}

export function ExportButton({ restaurants, type }: ExportButtonProps) {
  const handlePrint = () => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) {
      toast.error("Please allow popups to print");
      return;
    }

    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Localytics - ${type === "favorites" ? "My Favorites" : type === "comparison" ? "Restaurant Comparison" : "Restaurant Report"}</title>
          <style>
            body {
              font-family: Arial, sans-serif;
              padding: 40px;
              max-width: 1200px;
              margin: 0 auto;
            }
            h1 {
              color: #2563eb;
              border-bottom: 3px solid #2563eb;
              padding-bottom: 10px;
            }
            .restaurant {
              margin: 20px 0;
              padding: 20px;
              border: 1px solid #e2e8f0;
              border-radius: 8px;
              page-break-inside: avoid;
            }
            .restaurant h2 {
              color: #1e293b;
              margin: 0 0 10px 0;
            }
            .score {
              display: inline-block;
              background: #eff6ff;
              color: #1e40af;
              padding: 8px 16px;
              border-radius: 8px;
              font-size: 24px;
              font-weight: bold;
              margin: 10px 0;
            }
            .details {
              color: #64748b;
              margin: 10px 0;
            }
            .factors {
              margin: 15px 0;
            }
            .factor {
              margin: 8px 0;
              display: flex;
              justify-content: space-between;
              align-items: center;
            }
            .factor-bar {
              flex: 1;
              height: 20px;
              background: #e2e8f0;
              border-radius: 4px;
              margin: 0 10px;
              overflow: hidden;
            }
            .factor-fill {
              height: 100%;
              background: #2563eb;
            }
            .footer {
              margin-top: 40px;
              padding-top: 20px;
              border-top: 1px solid #e2e8f0;
              text-align: center;
              color: #64748b;
            }
          </style>
        </head>
        <body>
          <h1>Localytics - ${type === "favorites" ? "My Favorite Restaurants" : type === "comparison" ? "Restaurant Comparison" : "Restaurant Report"}</h1>
          <p style="color: #64748b; margin-bottom: 30px;">Richardson, TX • Generated on ${new Date().toLocaleDateString()}</p>
          
          ${restaurants
            .map(
              (restaurant) => `
            <div class="restaurant">
              <h2>${restaurant.name}</h2>
              <div class="details">
                <strong>${restaurant.cuisine}</strong> • ${restaurant.priceRange} • ${restaurant.distance} • ${restaurant.address}
              </div>
              <div class="score">${restaurant.overallScore}/100</div>
              <div class="factors">
                <h3>Score Breakdown:</h3>
                ${restaurant.factors
                  .map(
                    (factor) => `
                  <div class="factor">
                    <span style="width: 150px;">${factor.name}</span>
                    <div class="factor-bar">
                      <div class="factor-fill" style="width: ${factor.score}%"></div>
                    </div>
                    <span style="width: 50px; text-align: right;"><strong>${factor.score}</strong></span>
                  </div>
                `
                  )
                  .join("")}
              </div>
              ${
                restaurant.description
                  ? `<p style="margin-top: 15px; color: #475569;"><em>${restaurant.description}</em></p>`
                  : ""
              }
            </div>
          `
            )
            .join("")}
          
          <div class="footer">
            <p>Generated by Localytics • Data-driven dining decisions</p>
            <p>Visit us at your-localytics-url.com</p>
          </div>
        </body>
      </html>
    `;

    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.onload = () => {
      printWindow.print();
    };
    toast.success("Opening print dialog...");
  };

  const handleExportCSV = () => {
    const headers = ["Name", "Cuisine", "Score", "Price", "Distance", "Address"];
    const rows = restaurants.map((r) => [
      r.name,
      r.cuisine,
      r.overallScore.toString(),
      r.priceRange,
      r.distance,
      r.address,
    ]);

    const csvContent = [headers, ...rows].map((row) => row.join(",")).join("\n");
    const blob = new Blob([csvContent], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `localytics-${type}-${new Date().toISOString().split("T")[0]}.csv`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("CSV file downloaded!");
  };

  if (restaurants.length === 0) {
    return null;
  }

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" className="gap-2">
          <Download className="w-4 h-4" />
          Export
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={handlePrint}>
          <Printer className="w-4 h-4 mr-2" />
          Print Report
        </DropdownMenuItem>
        <DropdownMenuItem onClick={handleExportCSV}>
          <Download className="w-4 h-4 mr-2" />
          Export as CSV
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
